version: '3.7'

services:

  api:
    container_name: rest-api
    restart: always
    build:
      context: ./webapp/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./webapp/server:/app

  client:
    container_name: react-frontend
    build:
      context: ./webapp/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp/client:/app
      - '/app/node_modules'

  nginx:
    restart: always
    container_name: nginx-server
    build:
      context: ./webapp/nginx
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - "api"
      - "client"
