version: '3.7'

services:
  server:
    container_name: rest-api
    restart: always
    build:
      context: ./webapp/server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./webapp/server:/app

  client:
    container_name: react-frontend
    build:
      context: ./webapp/client
      dockerfile: Dockerfile.dev
    volumes:
      - ./webapp/client:/app
      - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - "server"
